# Generated by Django 5.0.1 on 2025-05-07 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyjeqrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
