# Generated by Django 5.0.1 on 2025-05-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyjeqrcodes', '0002_alter_qrcode_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='lien',
            field=models.CharField(max_length=1000),
        ),
    ]
