# Generated by Django 5.0.1 on 2025-05-08 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyjeqrcodes', '0003_alter_qrcode_lien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodevisit',
            name='dateVisite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
