# Generated by Django 5.0.1 on 2025-05-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyjeqrcodes', '0004_alter_qrcodevisit_datevisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyjeqrcodes.qrcode')),
            ],
        ),
        migrations.AddField(
            model_name='qrcodevisit',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyjeqrcodes.designqrcode'),
        ),
        migrations.CreateModel(
            name='LieuQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyjeqrcodes.qrcode')),
            ],
        ),
        migrations.AddField(
            model_name='qrcodevisit',
            name='lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyjeqrcodes.lieuqrcode'),
        ),
    ]
