# Generated by Django 5.0.1 on 2025-05-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyjeqrcodes', '0005_designqrcode_qrcodevisit_design_lieuqrcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='type',
            field=models.CharField(choices=[('Affiche', 'Affiche'), ('Autre', 'Autre')], default='Autre', max_length=20),
        ),
    ]
